### ISSUE TITLE
Unable to archive task

### ISSUE THREAD

**Issue by fayimora** [EgorKulikov/idea-chelper#37]
I opened an old project today to play with some problems. Restoring and running tasks worked fine but I seem to be unable to archive them. The project in question is [fayimora/uva](https://github.com/fayimora/uva) and the error I get is:

<img width="522" alt="screenshot 2016-05-19 18 12 51" src="https://cloud.githubusercontent.com/assets/648684/15402754/b3b47c32-1ded-11e6-9fff-1b0ad26fe726.png">

I'm currently using V4.1.3. The last time i used the project, it was using v3.0

Any idea how to fix this?

cc @EgorKulikov

**Comment by fayimora** [comment]
When I restore a task, it seems the files for that task are still kept in the archive 😢

**Comment by EgorKulikov** [comment]
They are. On windows you can archive again without problems. I'll think about what can be done to avoid this

**Comment by fayimora** [comment]
@EgorKulikov any chance you've had a look at this... by the way I am on MacOS.

**Comment by fayimora** [comment]
Ping @EgorKulikov

**Comment by fayimora** [comment]
@EgorKulikov any update on this?

**Comment by scruel** [comment]
@fayimora could you be more specific? like, show me your full StackTrace.
