### ISSUE TITLE
Not working for hacker rank with chrome extension

### ISSUE THREAD

**Issue by shankyty** [EgorKulikov/idea-chelper#41]
Since hacker rank dom is updated exsiting parser fails to parse contest name.

**Comment by shankyty** [comment]
https://github.com/EgorKulikov/idea-chelper/pull/42

**Comment by shankyty** [comment]
please   update

**Comment by jmerle** [comment]
Until the pull request is merged and the plugin is updated, the Javascript below will make the HackerRank problems compatible with the current version of CHelper. Can be ran with a Userscript Manager like Tampermonkey or Greasemonkey, just paste it in there and make it run on all HackerRank challenge pages. The only thing you need to adjust is the `Test type`, which you manually have to set to `Single test`.

```javascript
(function() {
  'use strict';

  const run = () => {
    $('.challenge_sample_input pre, .challenge_sample_output pre').each(function() {
      const html = $(this).html();
      $(this).html('<span class="err"></span>' + html.substr(6, html.length - 13));
    });
  };

  const runWhenProblemLoaded = () => {
    if ($('.challenge_sample_input').length > 0) {
      run();
    } else {
      setTimeout(runWhenProblemLoaded, 50);
    }
  };

  runWhenProblemLoaded();
})();
```

**Comment by satahippy** [comment]
Guys, any updates?

**Comment by shankyty** [comment]
Its already merged

**Comment by satahippy** [comment]
Yeah, but what about #45 ?

**Comment by Arpit0492** [comment]
does anyone care to specify install instructions for this extension, I have tried but didn't work out.

**Comment by shankyty** [comment]
Not merged

**Comment by satahippy** [comment]
@Arpit0492 I used IDEA plugin installer (from settings).
The plugin has installed successfully, but I'm not able to use it for hackerrank.

**Comment by shankyty** [comment]
@satahippy let me check this

**Comment by satahippy** [comment]
@shankyty I'm using the plugin from IDEA plugins repository (version 4.1.10).
Here it is: [CHelper 4.1.10](https://plugins.jetbrains.com/plugin/7091-chelper/update/34115).

**Comment by Arpit0492** [comment]
Thank you for replies guys. I will do as instructed. Hope it works this time.

**Comment by scruel** [comment]
I‘m working on this project, If there is anything you need, just let me know, I may fix it when I have time.  
here is my forked respority: [https://github.com/scruel/idea-chelper](https://github.com/scruel/idea-chelper)  
you can check the commit recodes to find out what I have done.

**Comment by jmerle** [comment]
I am using a userscript to fix this issue (even though it's better to fix it in CHelper itself, but this works aswell). It basically changes the url so that the extension detects it's a HackerRank problem and then changes the html of the tests and the breadcrumbs so that the tests and the contest name are correctly parsed by CHelper. The only down-side is that it messes up the browser's history.

Source:
https://gist.github.com/jmerle/acc814854ade4924036d83d828a9e5eb

If you have a userscript manager installed (I use Tampermonkey, should also work with Greasemonkey), simply click Raw on the right side of the Gist file and an installation window will show.

**Comment by jmerle** [comment]
I fixed this issue for myself with a userscript which adds support for custom parsers:
https://github.com/jmerle/chelper-custom-parsers

**Comment by EdNgulele** [comment]
Thank you so much!!!
 @jmerle
