### ISSUE TITLE
Error after parsing from Hackerearth

### ISSUE THREAD

**Issue by khokharnikunj8** [EgorKulikov/idea-chelper#48]
I can successfully parse problem from Hackerearth. but after parsing , chelper does not compiles my program.

**Comment by scruel** [comment]
I'm working on this project, could you be more specific? like more details texts, videos or any thing else will be helpful. It seems EgorKulikov doesn't have time for now. and I have done lots, I may solve your problem when I have time.

**Comment by khokharnikunj8** [comment]
Problem is resolved many times ago. Thanks for response.
