### ISSUE TITLE
Error parsing problems from Codechef Practice Section

### ISSUE THREAD

**Issue by khokharnikunj8** [EgorKulikov/idea-chelper#50]

**Comment by jmerle** [comment]
CodeChef's practice problems work in my [CHelper Companion](https://github.com/jmerle/chelper-companion) extension, available for [Chrome](https://chrome.google.com/webstore/detail/chelper-companion/cjnmckjndlpiamhfimnnjmnckgghkjbl) and [Firefox](https://addons.mozilla.org/en-US/firefox/addon/chelper-companion/).

**Comment by khokharnikunj8** [comment]
@jmerle  not working... I used extension. Whenever I have tried to  parse from codechef, CHelper: Unable to parse task from csacademy message is coming.

**Comment by jmerle** [comment]
Which problem are you trying to parse? I tested it on the Enormous Input problem and it works fine.

**Comment by khokharnikunj8** [comment]
try this : https://www.hackerrank.com/challenges/grid-challenge/problem @jmerle

**Comment by jmerle** [comment]
That's not CodeChef, and it works for me:
![](https://i.imgur.com/akjRQft.png)

**Comment by khokharnikunj8** [comment]
@jmerle Chelper version ?

**Comment by jmerle** [comment]
CHelper version 4.1.10, CHelper Companion version 1.0.0

**Comment by khokharnikunj8** [comment]
@jmerle  Nice work... I was using 4.1.11 beta so.... I changed it to 4.1.10 and using Chelper Companion , Works perfect. thank you

**Comment by jmerle** [comment]
I will make a fix for 4.1.11 today, apparently the CSAcademy parser was updated.

**Comment by jmerle** [comment]
I released 1.0.1 which fixes this issue and works with both 4.1.10 and 4.1.11. It's available from both the Chrome Web Store and Mozilla's AMO. Existing installations will automatically be updated by the browser (unless you disabled automatic updates).

**Comment by khokharnikunj8** [comment]
@jmerle  Thanks.
