### ISSUE TITLE
Auxillary array in helper class becomes a primitive in production code

### ISSUE THREAD

**Issue by lancehaoh** [EgorKulikov/idea-chelper#59]
There is an issue with CHelper when generating output code.

In particular, code of the following form will have problem:

public class Main {
}

public HelperClass {
  int arr[];
}

In the output file "Main.java" generated by CHelper, HelperClass becomes a static class and arr[] object will become "int arr" instead of "int arr[]"

**Comment by EgorKulikov** [comment]
Will not fix, please do not use c++ style array declaration, use int[] arr;
