### ISSUE TITLE
Your IDEA Beta Plugin Could Work Normally

### ISSUE THREAD

**Issue by 553899811** [EgorKulikov/idea-chelper#62]
When I use chelper version-4.3.1 ,it can't work. I faill to run any TestCase .But when i change to Beta Version ,it became normally.
If you need,you can find here.
[IDEA Beta Plugin URL](http://plugins.jetbrains.com/plugin/7091-chelper/update/47569)

**Comment by EgorKulikov** [comment]
I am glad beta version works. I hope to release it to stable in a week or so
