### ISSUE TITLE
Solution isn't auto recompiled

### ISSUE THREAD

**Issue by ntviet18** [EgorKulikov/idea-chelper#65]
Hi @EgorKulikov ,

I noticed that before run or copy source the solution isn't recompiled. Is that intentional or I mis-configured it?

I'm using: Intellij 2018.2, CHelper 4.3.1

**Comment by EgorKulikov** [comment]
It should not be recompiled before copy source button
There was an issue with idea 2018.2 that was fixed in 4.4.1+. Let me know if you still experience any problems

**Comment by ntviet18** [comment]
Hi @EgorKulikov , awesome fix
Thank you very much

**Comment by ntviet18** [comment]
@EgorKulikov , thank you again
I have checked and it recompile before run now
