### ISSUE TITLE
Exception in thread "main" java.lang.ClassNotFoundException: Codes.TaskA

### ISSUE THREAD

**Issue by rishabhdeepsingh** [EgorKulikov/idea-chelper#70]
While trying to run the Task on Windows i am getting the Following error. What to do?
I tried reinstalling the Plugin but still not working.    

    Exception in thread "main" java.lang.ClassNotFoundException: Codes.TaskA
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:338)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at net.egork.chelper.tester.NewTester.test(NewTester.java:81)
	at net.egork.chelper.tester.NewTester.main(NewTester.java:34)

**Comment by blue-atom** [comment]
@rishabhdeepsingh   Can you be more specific about steps to reproduce this error?

Which IDE are you using?
How exactly can this error be reproduced?


My initial thoughts about what is going wrong (_**for contributors**_)
In "NewTest.java"
1) Received "args" is not proper, possible reason: some other part of the program which is responsible for creating a test is malfunctioning and passing bad arguments
2) for some reason the file provided in "args" doesn't exist or have bad content

**Comment by rishabhdeepsingh** [comment]
I am using
```
IntelliJ IDEA 2018.1.3 (Ultimate Edition)
Build #IU-181.4892.42, built on May 8, 2018
Licensed to RISHABHDEEP SINGH
Subscription is active until May 5, 2019
JRE: 1.8.0_152-release-1136-b38 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
```
I Dont know it just stoped somehow.

**Comment by blue-atom** [comment]
okay i will try to reproduce the error, thanks

**Comment by rishabhdeepsingh** [comment]
Maybe if u reset the Archive folder it shows then

**Comment by rishabhdeepsingh** [comment]
After updating IntelliJ Idea the issue is Resolved.

**Comment by blue-atom** [comment]
Great!!

**Comment by blue-atom** [comment]
@rishabhdeepsingh can you please close this issue
