### ISSUE TITLE
Variables type working wrong. Have specific case to reproduce.

### ISSUE THREAD

**Issue by prituladima** [EgorKulikov/idea-chelper#74]
Egor, your plugin will live forever! It's very helpfull and let me focus on task and not waste my time on routine. 
I found interesting bug so far.
Fields like:
int[][][] dp; are working fine;
int dp[][][]: are working fine but generate wrong .java file  with int dp; field.
Here is the submission from CF.
https://codeforces.com/contest/1031/submission/48768707
Very minor bug. Just to keep you posted.

**Comment by jmerle** [comment]
Seems to be identical to #59, which will not be fixed.
