### ISSUE TITLE
Running a task ignores tests

### ISSUE THREAD

**Issue by sharoha** [EgorKulikov/idea-chelper#78]
I parsed a problem directly from Codeforces(this correctly parses all the test). Add a few tests by myself. But after running the task Chelper automatically skips some test, even though the JSON has an active property for every test to 'true'.
Attached a screenshot for evidence

![Screenshot (1)](https://user-images.githubusercontent.com/16621172/64287008-3abefc00-cf7c-11e9-87ba-8064f0c9b92d.png)

**Comment by EgorKulikov** [comment]
You probably have “Smart testing” enabled. When it is enabled it only runs on first failed test from last run (and after it got passed - on all tests)

**Comment by sharoha** [comment]
Thank you for the response. I looked it in my setting and found that this is indeed the case.
