### ISSUE TITLE
CHelper: Unable to parse task from json

### ISSUE THREAD

**Issue by mafulafunk** [EgorKulikov/idea-chelper#81]
Using the Competitive Companion in Chrome genereates 

23:46	CHelper: Unable to parse task from json

In the Event Log.

Dump of the Chrome plugin to the console:

{
    "name": "B. Badge",
    "group": "Codeforces - Codeforces Round #503 (by SIS, Div. 2)",
    "url": "https://codeforces.com/problemset/problem/1020/B",
    "interactive": false,
    "memoryLimit": null,
    "timeLimit": null,
    "tests": [
        {
            "input": "3\n2 3 2\n",
            "output": "2 2 3 \n"
        },
        {
            "input": "3\n1 2 3\n",
            "output": "1 2 3 \n"
        }
    ],
    "testType": "single",
    "input": {
        "fileName": "input",
        "type": "file"
    },
    "output": {
        "fileName": "output",
        "type": "file"
    },
    "languages": {
        "java": {
            "mainClass": "Main",
            "taskClass": "BBadge"
        }
    }
}

**Comment by EgorKulikov** [comment]
Well. I'd venture this is due to nulls in time/memory limit fields. And those are passed from competitive companion, so nothing I can do

**Comment by jmerle** [comment]
I have fixed the bug in Competitive Companion in https://github.com/jmerle/competitive-companion/commit/da1ec823b0f7e2fff0d07b9b9b30f21a086519c4, this issue can be closed.
